// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyWeb.Models
{
    public partial class Customer
    {
        [Key]
        public int CID { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "會員姓名")]
        public string C_Name { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "會員電話")]
        public string C_CellPhone { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "會員Email")]
        public string C_AC_Email { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "會員密碼")]
        public string C_Password { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "地址")]
        public string C_Address { get; set; }
    }
}