// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyWeb.Models
{
    public partial class Employee
    {
        [Key]
        [Display(Name = "員工編號")]
        public int EmployeeID { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "員工姓名")]
        public string E_Name { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "帳號")]
        public string E_Account { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "密碼")]
        public string E_Password { get; set; }
        [Display(Name = "電話")]
        public int E_Phone { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Email")]
        public string E_Email { get; set; }
    }
}