// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyWeb.Models
{
    public partial class Meal
    {
        [Key]
        public int MID { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "店家名稱")]
        public string R_Name { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "餐點名稱")]
        public string M_Name { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "餐點資訊")]
        public string M_InFo { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "餐點價格")]
        public string M_Price { get; set; }
        
        [Display(Name = "餐點照片")]
        public string M_ImgFile { get; set; }
    }
}