// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MyWeb.Models
{
    public partial class Restaurant
    {
        [Key]
        public int RID { get; set; }
        [Required(ErrorMessage = "*店家名稱為必填欄位")]
        [StringLength(50)]
        [Display(Name = "店家名稱")]
        
        public string RestaurantName { get; set; }
        [Required(ErrorMessage = "*店家電話為必填欄位")]
        [StringLength(50)]
        [Display(Name = "店家電話")]
        public string R_Phone { get; set; }
        [Required(ErrorMessage = "*店家地址為必填欄位")]
        [StringLength(50)]
        [Display(Name = "店家地址")]
        public string R_Address { get; set; }
        [Required(ErrorMessage = "*聯絡人為必填欄位")]
        [StringLength(50)]
        [Display(Name = "聯絡人")]
        public string R_Contact { get; set; }
        [Required(ErrorMessage = "*聯絡人電話為必填欄位")]
        [StringLength(50)]
        [Display(Name = "聯絡人電話")]
        public string R_C_Cellphone { get; set; }
        
        [Display(Name = "店家照片")]
        public string R_ImgFile { get; set; }
    }
}